### ISSUE TITLE
Maven plugin compatibility broken

### ISSUE THREAD

**Issue by NoMaillard** [JVoiceXML/JVoiceXML#53]
the maven plugin expects two variables to install Jars into the repo: 
`version`
`group`

theses variables no longer exist in the gradle properties

**Comment by schnelle** [comment]
I set them to the values of
JVOICEXML_GROUP
JVOICEXML_VERSION
wherever I found they were missing. Please, state explicitly the place where the error occurs.

Or is it more due to the fact that maven cannot resolve these values at all?
In that case, I need to understand better the way you are using it.

**Comment by NoMaillard** [comment]
maven needs these at the project level (not sure if there's an other way than in the gradle.properties file) to be able to install de jars in the repo, otherwise they get installed in `JVoiceXml/unspecified`.

this happens for all packages

**Comment by schnelle** [comment]
Yes.

**Comment by schnelle** [comment]
Try adding
group=JVOICEXML_GROUP
version=JVOICEXML_VERSION
to gradle.properties after the values are defined.

**Comment by NoMaillard** [comment]
this also does not work since gradle.propreties is just a plain file and nothing is evaluated in it.
this installs the jars at JVOICEXML_GROUP/JVOICEXML_VERSION in the maven repository

**Comment by schnelle** [comment]
OK. Now I was able to reproduce your issue. Should work now.

**Comment by schnelle** [comment]
Resolved
